/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package salsabila_view;

import salsabila_controller.mahasiswacontroller;
import javax.swing.JComboBox;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author Vava
 */
public class formmahasiswa extends javax.swing.JFrame {

    /**
     * Creates new form formmahasiswa
     */
    private mahasiswacontroller controller;
    public formmahasiswa(){
        initComponents();
        controller = new mahasiswacontroller(this);
        controller.cancel();
        controller.viewData();
         
    }

    public JTable getTablemahasiswa() {
        return tablemahasiswa;
    }

    public JComboBox<String> getCbojeniskelamin() {
        return cbojeniskelamin;
    }
    

    public JTextField getTxtalamat() {
        return txtalamat;
    }

    public JTextField getTxtnama() {
        return txtnama;
    }

    public JTextField getTxtnobp() {
        return txtnobp;
    }

    public JTextField getTxttanggallahir() {
        return txttanggallahir;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtnobp = new javax.swing.JTextField();
        txttanggallahir = new javax.swing.JTextField();
        txtnama = new javax.swing.JTextField();
        txtalamat = new javax.swing.JTextField();
        cbojeniskelamin = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        btnupdate = new javax.swing.JButton();
        btndelete = new javax.swing.JButton();
        btncancel = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        btninsert = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablemahasiswa = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setText("nobp");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(26, 16, 28, 16);

        jLabel2.setText("nama");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(26, 44, 30, 16);

        jLabel3.setText("alamat");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(26, 70, 40, 16);

        jLabel4.setText("jeniskelamin");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(26, 100, 70, 16);

        txtnobp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnobpActionPerformed(evt);
            }
        });
        getContentPane().add(txtnobp);
        txtnobp.setBounds(140, 10, 230, 20);

        txttanggallahir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttanggallahirActionPerformed(evt);
            }
        });
        getContentPane().add(txttanggallahir);
        txttanggallahir.setBounds(140, 130, 230, 22);
        getContentPane().add(txtnama);
        txtnama.setBounds(140, 40, 230, 20);
        getContentPane().add(txtalamat);
        txtalamat.setBounds(140, 70, 230, 20);

        cbojeniskelamin.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(cbojeniskelamin);
        cbojeniskelamin.setBounds(140, 100, 72, 22);

        jLabel5.setText("tanggal lahir");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(20, 130, 80, 20);

        btnupdate.setText("update");
        btnupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdateActionPerformed(evt);
            }
        });
        getContentPane().add(btnupdate);
        btnupdate.setBounds(110, 190, 72, 23);

        btndelete.setText("delete");
        btndelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeleteActionPerformed(evt);
            }
        });
        getContentPane().add(btndelete);
        btndelete.setBounds(190, 190, 72, 23);

        btncancel.setText("cancel");
        btncancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancelActionPerformed(evt);
            }
        });
        getContentPane().add(btncancel);
        btncancel.setBounds(270, 190, 72, 23);

        jButton4.setText("Exit");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(150, 220, 72, 23);

        btninsert.setText("insert");
        btninsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btninsertActionPerformed(evt);
            }
        });
        getContentPane().add(btninsert);
        btninsert.setBounds(30, 190, 72, 23);

        tablemahasiswa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "nobp", "nama", "alamat", "jekel", "tgllahir"
            }
        ));
        tablemahasiswa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablemahasiswaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablemahasiswa);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 250, 380, 280);

        setSize(new java.awt.Dimension(416, 560));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txttanggallahirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttanggallahirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttanggallahirActionPerformed

    private void btninsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btninsertActionPerformed
        // TODO add your handling code here:
        controller.insert();
        controller.viewData();
        controller.cancel();
        
    }//GEN-LAST:event_btninsertActionPerformed

    private void btncancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelActionPerformed
        // TODO add your handling code here:
        controller.cancel();
    }//GEN-LAST:event_btncancelActionPerformed

    private void txtnobpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnobpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnobpActionPerformed

    private void tablemahasiswaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablemahasiswaMouseClicked
        // TODO add your handling code here:
        controller.getmahasiswa();
    }//GEN-LAST:event_tablemahasiswaMouseClicked

    private void btnupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdateActionPerformed
        // TODO add your handling code here:
        controller.update();
        controller.viewData();
        controller.cancel();
        
    }//GEN-LAST:event_btnupdateActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void btndeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeleteActionPerformed
        // TODO add your handling code here:
        controller.delete();
        controller.viewData();
        controller.cancel();
        
    }//GEN-LAST:event_btndeleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formmahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formmahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formmahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formmahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formmahasiswa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncancel;
    private javax.swing.JButton btndelete;
    private javax.swing.JButton btninsert;
    private javax.swing.JButton btnupdate;
    private javax.swing.JComboBox<String> cbojeniskelamin;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablemahasiswa;
    private javax.swing.JTextField txtalamat;
    private javax.swing.JTextField txtnama;
    private javax.swing.JTextField txtnobp;
    private javax.swing.JTextField txttanggallahir;
    // End of variables declaration//GEN-END:variables
}
